# Generated by Django 4.2.7 on 2023-11-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_transaccion_cantidad_alter_transaccion_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='ingreso',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='limpia',
            field=models.CharField(max_length=10),
        ),
    ]
