# Generated by Django 4.2.7 on 2023-12-01 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_transaccion_fecha_alter_transaccion_ropa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='ingreso',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='limpia',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 21, 1, 47, 231529)),
        ),
    ]
